import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "World Film Archive",
  description: `Welcome to the World Film Archive, a digital gateway to the world's 
              most treasured film collections.
              This interactive website showcases a dynamic map highlighting film archive
              institutes across the globe.
              Discover where iconic reels are preserved, view detailed profiles of each institute,
              explore digitized collections, and learn about their history and cultural impact.
              Whether you're a researcher, filmmaker, or cinephile, this platform connects you
              to the institutions safeguarding the legacy of cinema.Generated by create next app`,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
